if(NOT DEFINED VCPKG_TARGET_TRIPLET)
    if(EMSCRIPTEN)
        set(VCPKG_TARGET_TRIPLET "wasm32-emscripten" CACHE STRING "WebAssembly triplet")
    elseif(ANDROID)
        if(CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
            set(VCPKG_TARGET_TRIPLET "arm64-android" CACHE STRING "Android ARM64 triplet")
        elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "x86_64")
            set(VCPKG_TARGET_TRIPLET "x64-android" CACHE STRING "Android x64 triplet")
        else()

            set(VCPKG_TARGET_TRIPLET "arm64-android" CACHE STRING "Default Android triplet")
        endif()
    else()
        if(WIN32)
            set(V_OS "windows")
        elseif(APPLE)
            set(V_OS "osx")
        elseif(UNIX)
            set(V_OS "linux")
        endif()

        set(V_ARCH "x64")
        if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
            set(V_ARCH "arm64")
        endif()

        set(VCPKG_TARGET_TRIPLET "${V_ARCH}-${V_OS}-static" CACHE STRING "Auto-detected desktop triplet")
    endif()

    message(STATUS "Auto-configuring vcpkg triplet: ${VCPKG_TARGET_TRIPLET}")
endif()
